// Monday February 27, 2023 - Sidney Basa

// connect express
const express = require('express');
// connect the mongoose ORM
const db = require('./config/connection');
// conect the routes
const allRoutes = require('./routes');

// Heroku configuration to allow Heroku to generate a port or default to 3001
const PORT = process.env.PORT || 3001;
const app = express();

// express middleware
app.use(express.urlencoded({ extended: true }));
app.use(express.json());

// point express to the routes
app.use(allRoutes);

// once the database has run
// start listening for routes at the default of 3001 unless generated by heroku
db.once('open', () => {app.listen(PORT, () => {console.log(`Server is running on port ${PORT}`);});});
